#!/bin/bash

if [ -d "tmp" ]; then
  find tmp/ -name "*.txt" -print0 | xargs -0 rm -rf
  find tmp/ -name "*.php" -print0 | xargs -0 rm -rf
elif [ -d "source" ]; then
  find source/tmp/ -name "*.txt" -print0 | xargs -0 rm -rf
  find source/tmp/ -name "*.php" -print0 | xargs -0 rm -rf
else
  echo "tmp or soruce directory not found, run this command in the shop root or source directory"
fi
