#!/bin/bash

if [ -f "metadata.php" ]; then
  
  absModulePath=$PWD;
  currentdir="$(basename -- $PWD)";
  
  # echo "absolute module path: $absModulePath";
  # echo "basename: $currentdir";
  
  while [ $currentdir != "source" ]; do 
	cd ../;
    currentdir="$(basename -- $PWD)"
  done
  
  cd ../;
  shoproot=$PWD;
  # echo "shop root: $shoproot";
  
  relModulePath=${absModulePath:${#shoproot}+1};
  # echo "relative module path: $relModulePath";
  
  # running oxid console command
  eval "vendor/bin/oe-console oe:module:activate $relModulePath";
  
else
  echo "metadata.php not found, please run this command in a module directory"
fi